import type { ComponentType } from 'react';
import { Binary, Component as OopIcon } from 'lucide-react';
import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiNextdotjs,
  SiNestjs,
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiCss,
  SiHtml5,
  SiPython,
  SiCplusplus,
  SiC,
  SiSharp,
  SiDotnet,
  SiGo,
  SiRust,
  SiPhp,
  SiKotlin,
  SiSwift,
  SiDart,
  SiFlutter,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiSqlite,
  SiFirebase,
  SiSupabase,
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiCloudflare,
  SiDigitalocean,
  SiHeroku,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiLinux,
  SiUbuntu,
  SiNginx,
  SiPostman,
  SiInsomnia,
  SiFigma,
  SiCanva,
  SiNotion,
  SiSlack,
  SiJetbrains,
  SiIntellijidea,
  SiWebpack,
  SiVite,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiPrisma,
  SiGraphql,
  SiSocketdotio,
  SiRedux,
  SiZod,
  SiStorybook,
  SiTrpc,
  SiVuedotjs,
  SiNuxt,
  SiAngular,
  SiSvelte,
  SiAstro,
  SiRemix,
  SiTensorflow,
  SiPytorch,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiJupyter,
  SiOpenai,
  SiThreedotjs,
  SiBlender,
  SiUnity,
  SiUnrealengine,
  SiCodeforces,
  SiLeetcode,
  SiCodechef,
  SiDjango,
  SiJquery,
  SiDaisyui,
  SiShopify,
  SiCloudinary,
  // Build tools / package managers
  SiBun,
  SiDeno,
  SiRollupdotjs,
  SiEsbuild,
  SiBiome,
  SiPnpm,
  SiYarn,
  SiNpm,
  // Frontend frameworks / libs
  SiSolid,
  SiQwik,
  SiHtmx,
  SiAlpinedotjs,
  SiEmberdotjs,
  SiBackbonedotjs,
  SiPreact,
  SiLit,
  SiReactrouter,
  // UI kits
  SiChakraui,
  SiMui,
  SiAntdesign,
  SiRadixui,
  SiStyledcomponents,
  SiBulma,
  SiSemanticui,
  SiPostcss,
  // State / data fetching
  SiReactquery,
  SiRecoil,
  SiMobx,
  SiApollographql,
  SiSwr,
  // Backend frameworks
  SiFastify,
  SiKoa,
  SiFlask,
  SiFastapi,
  SiSpring,
  SiSpringboot,
  SiLaravel,
  SiSymfony,
  SiRubyonrails,
  SiRuby,
  SiGin,
  // Databases
  SiMariadb,
  SiCockroachlabs,
  SiApachecassandra,
  SiNeo4J,
  SiInfluxdb,
  SiElasticsearch,
  SiCouchbase,
  SiPlanetscale,
  SiTurso,
  // Cloud / DevOps
  SiTerraform,
  SiAnsible,
  SiJenkins,
  SiGithubactions,
  SiCircleci,
  SiTravisci,
  SiGrafana,
  SiPrometheus,
  SiDatadog,
  SiSentry,
  SiNewrelic,
  SiPodman,
  SiVagrant,
  SiPuppet,
  SiChef,
  SiNomad,
  SiConsul,
  SiVault,
  SiPulumi,
  // Auth / payments / comms
  SiStripe,
  SiPaypal,
  SiAuth0,
  SiOkta,
  SiClerk,
  SiTwilio,
  SiSendgrid,
  SiRazorpay,
  SiSquare,
  // Testing
  SiVitest,
  SiSelenium,
  SiMocha,
  SiJasmine,
  // Mobile
  SiIonic,
  SiAndroid,
  SiExpo,
  SiCapacitor,
  // Design
  SiSketch,
  SiFramer,
  SiWebflow,
  SiInvision,
  // CMS
  SiWordpress,
  SiContentful,
  SiSanity,
  SiStrapi,
  SiGhost,
  SiWix,
  SiSquarespace,
  SiDrupal,
  SiJoomla,
  // AI / ML
  SiHuggingface,
  SiLangchain,
  SiOllama,
  SiGooglegemini,
  // Web3 / blockchain
  SiEthereum,
  SiSolidity,
  SiWeb3Dotjs,
  SiBitcoin,
  SiPolygon,
  // Languages
  SiElixir,
  SiErlang,
  SiHaskell,
  SiScala,
  SiClojure,
  SiR,
  SiPerl,
  SiLua,
  // Monorepo / tooling
  SiTurborepo,
  SiNx,
  SiLerna,
  SiSwagger,
  SiWebassembly,
  SiElectron,
  SiTauri,
  // Analytics
  SiGoogleanalytics,
  SiMixpanel,
  SiHotjar,
  // Misc dev
  SiNodemon,
  SiChartdotjs,
  SiDotenv,
  SiYaml,
  SiJson,
  SiMarkdown,
  SiVim,
  SiNeovim,
  SiHomebrew,
} from 'react-icons/si';
import { FaJava, FaCode, FaAws } from 'react-icons/fa';
import {
  DiVisualstudio,
  DiMsqlServer,
  DiPhotoshop,
  DiIllustrator,
} from 'react-icons/di';
import { VscVscode } from 'react-icons/vsc';
import { GiTortoise } from 'react-icons/gi';

// Widened (not react-icons' own IconType) so lucide-react icons (Binary, OopIcon) can share this map — both libs accept `className`, which is all callers pass.
type IconComponent = ComponentType<{ className?: string }>;

// Keys are normalised skill names (lowercased, alphanumerics only) with aliases (e.g. "node"/"nodejs") for wider matches; unmatched skills fall back to FaCode via the caller.
const ICON_MAP: Record<string, IconComponent> = {
  // Web frameworks / runtimes
  react: SiReact,
  reactjs: SiReact,
  nextjs: SiNextdotjs,
  next: SiNextdotjs,
  nuxt: SiNuxt,
  nuxtjs: SiNuxt,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  sveltekit: SiSvelte,
  astro: SiAstro,
  remix: SiRemix,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  express: SiExpress,
  expressjs: SiExpress,
  nestjs: SiNestjs,
  nest: SiNestjs,

  // Languages
  typescript: SiTypescript,
  ts: SiTypescript,
  javascript: SiJavascript,
  js: SiJavascript,
  python: SiPython,
  py: SiPython,
  java: FaJava,
  c: SiC,
  cc: SiCplusplus,
  cpp: SiCplusplus,
  cplusplus: SiCplusplus,
  csharp: SiSharp,
  cs: SiSharp,
  dotnet: SiDotnet,
  net: SiDotnet,
  netcore: SiDotnet,
  aspnet: SiDotnet,
  aspnetcore: SiDotnet,
  django: SiDjango,
  jquery: SiJquery,
  go: SiGo,
  golang: SiGo,
  rust: SiRust,
  php: SiPhp,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  flutter: SiFlutter,

  // Markup / styling
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
  sass: SiSass,
  scss: SiSass,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  daisyui: SiDaisyui,
  htmlcss: SiHtml5,

  // Databases / data
  mongodb: SiMongodb,
  mongo: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  sqlite: SiSqlite,
  redis: SiRedis,
  firebase: SiFirebase,
  supabase: SiSupabase,
  prisma: SiPrisma,
  graphql: SiGraphql,
  sql: SiMysql,
  sqlmysql: SiMysql,
  sqlserver: DiMsqlServer,

  // Cloud / DevOps — AWS uses the FA glyph because react-icons v5 dropped the Si brand entry for it.
  aws: FaAws,
  amazonwebservices: FaAws,
  gcp: SiGooglecloud,
  googlecloud: SiGooglecloud,
  vercel: SiVercel,
  netlify: SiNetlify,
  cloudflare: SiCloudflare,
  digitalocean: SiDigitalocean,
  heroku: SiHeroku,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  nginx: SiNginx,
  linux: SiLinux,
  ubuntu: SiUbuntu,

  // Tools
  git: SiGit,
  github: SiGithub,
  gitgithub: SiGithub,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  postman: SiPostman,
  insomnia: SiInsomnia,
  figma: SiFigma,
  canva: SiCanva,
  notion: SiNotion,
  slack: SiSlack,
  vscode: VscVscode,
  visualstudio: DiVisualstudio,
  tortoisegit: GiTortoise,
  shopify: SiShopify,
  cloudinary: SiCloudinary,
  jetbrains: SiJetbrains,
  intellij: SiIntellijidea,
  webpack: SiWebpack,
  vite: SiVite,
  babel: SiBabel,
  eslint: SiEslint,
  prettier: SiPrettier,
  jest: SiJest,
  testinglibrary: SiTestinglibrary,
  rtl: SiTestinglibrary,
  cypress: SiCypress,
  storybook: SiStorybook,
  trpc: SiTrpc,

  // State / utility libs
  redux: SiRedux,
  zod: SiZod,
  socketio: SiSocketdotio,
  'socket.io': SiSocketdotio,

  // ML / data science
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  pandas: SiPandas,
  numpy: SiNumpy,
  scikitlearn: SiScikitlearn,
  sklearn: SiScikitlearn,
  jupyter: SiJupyter,
  openai: SiOpenai,

  // 3D / gaming
  threejs: SiThreedotjs,
  blender: SiBlender,
  unity: SiUnity,
  unreal: SiUnrealengine,
  unrealengine: SiUnrealengine,

  // CP platforms (mainly for tagging stats sections)
  codeforces: SiCodeforces,
  leetcode: SiLeetcode,
  codechef: SiCodechef,

  // Build tools / package managers
  bun: SiBun,
  deno: SiDeno,
  rollup: SiRollupdotjs,
  esbuild: SiEsbuild,
  biome: SiBiome,
  pnpm: SiPnpm,
  yarn: SiYarn,
  npm: SiNpm,

  // Frontend frameworks / libs
  solid: SiSolid,
  solidjs: SiSolid,
  qwik: SiQwik,
  htmx: SiHtmx,
  alpine: SiAlpinedotjs,
  alpinejs: SiAlpinedotjs,
  ember: SiEmberdotjs,
  emberjs: SiEmberdotjs,
  backbone: SiBackbonedotjs,
  backbonejs: SiBackbonedotjs,
  preact: SiPreact,
  lit: SiLit,
  reactnative: SiReact, // no dedicated Simple Icons brand — React Native shares the React atom logo
  reactrouter: SiReactrouter,

  // UI kits
  chakra: SiChakraui,
  chakraui: SiChakraui,
  mui: SiMui,
  materialui: SiMui,
  antdesign: SiAntdesign,
  antd: SiAntdesign,
  radixui: SiRadixui,
  radix: SiRadixui,
  styledcomponents: SiStyledcomponents,
  bulma: SiBulma,
  semanticui: SiSemanticui,
  postcss: SiPostcss,

  // State / data fetching
  reactquery: SiReactquery,
  tanstackquery: SiReactquery,
  recoil: SiRecoil,
  mobx: SiMobx,
  apollo: SiApollographql,
  apollographql: SiApollographql,
  swr: SiSwr,

  // Backend frameworks
  fastify: SiFastify,
  koa: SiKoa,
  flask: SiFlask,
  fastapi: SiFastapi,
  spring: SiSpring,
  springboot: SiSpringboot,
  laravel: SiLaravel,
  symfony: SiSymfony,
  rubyonrails: SiRubyonrails,
  rails: SiRubyonrails,
  ruby: SiRuby,
  gin: SiGin,

  // Databases
  mariadb: SiMariadb,
  cockroachdb: SiCockroachlabs,
  cassandra: SiApachecassandra,
  neo4j: SiNeo4J,
  influxdb: SiInfluxdb,
  elasticsearch: SiElasticsearch,
  couchbase: SiCouchbase,
  planetscale: SiPlanetscale,
  turso: SiTurso,

  // Cloud / DevOps
  terraform: SiTerraform,
  ansible: SiAnsible,
  jenkins: SiJenkins,
  githubactions: SiGithubactions,
  circleci: SiCircleci,
  travisci: SiTravisci,
  grafana: SiGrafana,
  prometheus: SiPrometheus,
  datadog: SiDatadog,
  sentry: SiSentry,
  newrelic: SiNewrelic,
  podman: SiPodman,
  vagrant: SiVagrant,
  puppet: SiPuppet,
  chef: SiChef,
  nomad: SiNomad,
  consul: SiConsul,
  vault: SiVault,
  pulumi: SiPulumi,

  // Auth / payments / comms
  stripe: SiStripe,
  paypal: SiPaypal,
  auth0: SiAuth0,
  okta: SiOkta,
  clerk: SiClerk,
  twilio: SiTwilio,
  sendgrid: SiSendgrid,
  razorpay: SiRazorpay,
  square: SiSquare,

  // Testing
  vitest: SiVitest,
  selenium: SiSelenium,
  mocha: SiMocha,
  jasmine: SiJasmine,

  // Mobile
  ionic: SiIonic,
  android: SiAndroid,
  expo: SiExpo,
  capacitor: SiCapacitor,
  capacitorjs: SiCapacitor,

  // Design
  sketch: SiSketch,
  photoshop: DiPhotoshop,
  adobephotoshop: DiPhotoshop,
  illustrator: DiIllustrator,
  adobeillustrator: DiIllustrator,
  framer: SiFramer,
  webflow: SiWebflow,
  invision: SiInvision,

  // CMS
  wordpress: SiWordpress,
  contentful: SiContentful,
  sanity: SiSanity,
  strapi: SiStrapi,
  ghost: SiGhost,
  wix: SiWix,
  squarespace: SiSquarespace,
  drupal: SiDrupal,
  joomla: SiJoomla,

  // AI / ML
  huggingface: SiHuggingface,
  langchain: SiLangchain,
  ollama: SiOllama,
  gemini: SiGooglegemini,
  googlegemini: SiGooglegemini,

  // Web3 / blockchain
  ethereum: SiEthereum,
  solidity: SiSolidity,
  web3: SiWeb3Dotjs,
  web3js: SiWeb3Dotjs,
  bitcoin: SiBitcoin,
  polygon: SiPolygon,

  // Languages
  elixir: SiElixir,
  erlang: SiErlang,
  haskell: SiHaskell,
  scala: SiScala,
  clojure: SiClojure,
  r: SiR,
  perl: SiPerl,
  lua: SiLua,

  // Monorepo / tooling
  turborepo: SiTurborepo,
  nx: SiNx,
  lerna: SiLerna,
  swagger: SiSwagger,
  openapi: SiSwagger,
  webassembly: SiWebassembly,
  wasm: SiWebassembly,
  electron: SiElectron,
  tauri: SiTauri,

  // Analytics
  googleanalytics: SiGoogleanalytics,
  mixpanel: SiMixpanel,
  hotjar: SiHotjar,

  // Misc dev
  nodemon: SiNodemon,
  chartjs: SiChartdotjs,
  dotenv: SiDotenv,
  yaml: SiYaml,
  json: SiJson,
  markdown: SiMarkdown,
  vim: SiVim,
  neovim: SiNeovim,
  homebrew: SiHomebrew,

  // CS concepts — no brand exists, so these use a representative lucide glyph instead of a react-icons logo.
  dsa: Binary,
  datastructuresalgorithms: Binary,
  oop: OopIcon,
  objectorientedprogramming: OopIcon,
};

// "#" is spelled out before stripping punctuation so "C#" normalises to "csharp" instead of colliding with plain "C".
const normalise = (input: string): string =>
  input
    .toLowerCase()
    .replace(/#/g, 'sharp')
    .replace(/[^a-z0-9]+/g, '');

/** Returns a react-icons component for a skill name, or null if no brand match — callers should render a fallback themselves. */
export function getSkillIcon(name: string): IconComponent | null {
  if (!name) return null;
  const key = normalise(name);
  return ICON_MAP[key] ?? null;
}

/** Fallback glyph for when no uploaded image or brand logo is available; re-exported so consumers don't need to import react-icons directly. */
export const FallbackSkillIcon: IconComponent = FaCode;
